# Introduction to PyTorch

## PyTorch compared to NumPy

In [2]:
import numpy as np
np.array([[2, 3, 5], [1, 2, 9]])

array([[2, 3, 5],
       [1, 2, 9]])

In [3]:
import torch
torch.tensor([[2, 3, 5], [1, 2, 9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [4]:
np.random.rand(2, 2)

array([[0.70825982, 0.28163597],
       [0.28271162, 0.72438809]])

In [9]:
torch.rand((2, 2))

tensor([[0.9227, 0.5962],
        [0.8918, 0.3908]])

In [6]:
a = np.random.randn(3, 5)
a.shape

(3, 5)

In [7]:
a = torch.rand((3, 5))
a.shape

torch.Size([3, 5])

## Matrix operations

In [12]:
a = np.random.rand(2, 2)
b = np.random.rand(2, 2)
np.dot(a, b)

array([[0.26221468, 0.69136735],
       [0.09846607, 0.80332514]])

In [13]:
np.multiply(a, b)

array([[0.25629228, 0.04963379],
       [0.00723387, 0.74270029]])

In [14]:
a = torch.rand((2, 2))
b = torch.rand((2, 2))
torch.matmul(a, b)   # Matrix product of two tensors

tensor([[0.1280, 0.8365],
        [0.0354, 0.3139]])

In [15]:
a * b

tensor([[0.0236, 0.3271],
        [0.0771, 0.0722]])

## Zeros and 