# Introduction to PyTorch

## PyTorch compared to NumPy

In [1]:
import numpy as np
np.array([[2, 3, 5], [1, 2, 9]])

array([[2, 3, 5],
       [1, 2, 9]])

In [2]:
import torch
torch.tensor([[2, 3, 5], [1, 2, 9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [3]:
np.random.rand(2, 2)

array([[0.51255002, 0.64964171],
       [0.9176648 , 0.4809319 ]])

In [4]:
torch.rand((2, 2))

tensor([[0.0917, 0.8352],
        [0.4473, 0.2391]])

In [5]:
a = np.random.randn(3, 5)
a.shape

(3, 5)

In [6]:
a = torch.rand((3, 5))
a.shape

torch.Size([3, 5])

## Matrix operations

In [7]:
a = np.random.rand(2, 2)
b = np.random.rand(2, 2)
np.dot(a, b)

array([[1.11029891, 0.45465814],
       [1.08632733, 0.41485761]])

In [8]:
np.multiply(a, b)

array([[0.70498012, 0.30087853],
       [0.44038768, 0.08794654]])

In [9]:
a = torch.rand((2, 2))
b = torch.rand((2, 2))
torch.matmul(a, b)   # Matrix product of two tensors

tensor([[0.5041, 0.5262],
        [1.0446, 1.1968]])

In [10]:
a * b

tensor([[0.0639, 0.2213],
        [0.9118, 0.7384]])

## Zeros and 

In [15]:
torch.zeros(1,1,5)

tensor([[[0., 0., 0., 0., 0.]]])